services:
  mysql:
    image: mysql:8.0
    container_name: novamart-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: novamart
    ports:
      - "3306:3306"
    volumes:
      - novamart_data:/var/lib/mysql

volumes:
  novamart_data:
